import { Product, Category } from '@/types'
export const mockCategories: Category[] = [
  {
    id: '1',
    slug: 'pots',
    nameRu: 'Горшки и кашпо',
    nameUz: 'Guldonlar',
    icon: '🪴',
    sortOrder: 1,
    isActive: true,
    productCount: 119,
  },
  {
    id: '2',
    slug: 'artificial-plants',
    nameRu: 'Искусственные растения',
    nameUz: "Sun'iy o'simliklar",
    icon: '🌿',
    sortOrder: 2,
    isActive: true,
    productCount: 21,
  },
  {
    id: '3',
    slug: 'plant-stands',
    nameRu: 'Подставки',
    nameUz: 'Tagliklar',
    icon: '🏗️',
    sortOrder: 3,
    isActive: true,
    productCount: 31,
  },
]

export const mockProducts: Product[] = [
  {
    id: '1',
    code: 'Artiplant-1',
    slug: 'artiplant-1',
    nameRu: 'Артиплант-1',
    nameUz: 'Artiplant-1',
    descriptionRu: 'Сделан из прочной пластмассы. Доступен в двух цветах: Черный, Белый.',
    descriptionUz: "Bardoshli plastmassadan tayyorlangan. Ikki rangda mavjud: Qora, Oq",
    categoryId: '1',
    price: 170000,
    material: 'plastic',
    dimensions: {
      diameter_cm: 30,
      height_cm: 51,
      volume_liters: 28,
    },
    inStock: true,
    stockQuantity: 50,
    setQuantity: 1,
    images: [
      { id: '1', url: 'https://placehold.co/400x400/22c55e/white?text=Artiplant-1', isMain: true, sortOrder: 0 },
    ],
    colors: [
      { id: '1', nameRu: 'Чёрный', nameUz: 'Qora', hexCode: '#000000', inStock: true, priceModifier: 0 },
      { id: '2', nameRu: 'Белый', nameUz: 'Oq', hexCode: '#FFFFFF', inStock: true, priceModifier: 0 },
    ],
    variants: [],
    isActive: true,
    isFeatured: true,
    isNew: false,
    viewCount: 150,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    code: 'Florence-1',
    slug: 'florence-1',
    nameRu: 'Флоренс-1',
    nameUz: 'Florence-1',
    descriptionRu: 'Сделан из прочной пластмассы. Доступен в трёх цветах.',
    descriptionUz: "Bardoshli plastmassadan tayyorlangan. Uch xil rangda mavjud.",
    categoryId: '1',
    price: 405000,
    oldPrice: 450000,
    material: 'plastic',
    dimensions: {
      diameter_cm: 35,
      height_cm: 62,
      volume_liters: 47,
    },
    inStock: true,
    stockQuantity: 30,
    setQuantity: 1,
    images: [
      { id: '2', url: 'https://placehold.co/400x400/16a34a/white?text=Florence-1', isMain: true, sortOrder: 0 },
    ],
    colors: [
      { id: '3', nameRu: 'Белый', nameUz: 'Oq', hexCode: '#FFFFFF', inStock: true, priceModifier: 0 },
      { id: '4', nameRu: 'Чёрный', nameUz: 'Qora', hexCode: '#000000', inStock: true, priceModifier: 0 },
      { id: '5', nameRu: 'Серый', nameUz: 'Kulrang', hexCode: '#6B7280', inStock: true, priceModifier: 0 },
    ],
    variants: [],
    isActive: true,
    isFeatured: true,
    isNew: true,
    viewCount: 200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    code: 'Botanik-02',
    slug: 'botanik-02',
    nameRu: 'Ботаник-02',
    nameUz: 'Botanik-02',
    descriptionRu: 'Сделан из прочной пластмассы. Доступен в четырёх цветах.',
    descriptionUz: "Bardoshli plastmassadan tayyorlangan. To'rt rangda mavjud.",
    categoryId: '1',
    price: 135000,
    material: 'plastic',
    dimensions: {
      diameter_cm: 27,
      height_cm: 28,
      volume_liters: 16,
    },
    inStock: true,
    stockQuantity: 100,
    setQuantity: 1,
    images: [
      { id: '3', url: 'https://placehold.co/400x400/15803d/white?text=Botanik-02', isMain: true, sortOrder: 0 },
    ],
    colors: [
      { id: '6', nameRu: 'Чёрный', nameUz: 'Qora', hexCode: '#000000', inStock: true, priceModifier: 0 },
      { id: '7', nameRu: 'Белый', nameUz: 'Oq', hexCode: '#FFFFFF', inStock: true, priceModifier: 0 },
      { id: '8', nameRu: 'Бежевый', nameUz: 'Bej', hexCode: '#D4A574', inStock: true, priceModifier: 0 },
    ],
    variants: [],
    isActive: true,
    isFeatured: false,
    isNew: true,
    viewCount: 80,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    code: 'Venice-52',
    slug: 'venice-52',
    nameRu: 'Венеция-52',
    nameUz: 'Venice-52',
    descriptionRu: 'Элегантный горшок из прочной пластмассы.',
    descriptionUz: "Nafis plastmassa guldon.",
    categoryId: '1',
    price: 565000,
    material: 'plastic',
    dimensions: {
      diameter_cm: 36,
      height_cm: 46,
      volume_liters: 47,
    },
    inStock: true,
    stockQuantity: 25,
    setQuantity: 1,
    images: [
      { id: '4', url: 'https://placehold.co/400x400/166534/white?text=Venice-52', isMain: true, sortOrder: 0 },
    ],
    colors: [
      { id: '9', nameRu: 'Чёрный', nameUz: 'Qora', hexCode: '#000000', inStock: true, priceModifier: 0 },
      { id: '10', nameRu: 'Белый', nameUz: 'Oq', hexCode: '#FFFFFF', inStock: true, priceModifier: 0 },
    ],
    variants: [],
    isActive: true,
    isFeatured: true,
    isNew: false,
    viewCount: 120,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    code: 'NEX21001',
    slug: 'nex21001',
    nameRu: 'NEX21001 (Набор 3 шт)',
    nameUz: 'NEX21001 (3 dona)',
    descriptionRu: 'Набор из трёх металлических горшков.',
    descriptionUz: "Uch dona metall guldonlar to'plami.",
    categoryId: '1',
    price: 290000,
    material: 'metal',
    dimensions: {
      size: '72x64x56',
    },
    inStock: true,
    stockQuantity: 15,
    setQuantity: 3,
    images: [
      { id: '5', url: 'https://placehold.co/400x400/374151/white?text=NEX21001', isMain: true, sortOrder: 0 },
    ],
    colors: [
      { id: '11', nameRu: 'Чёрный', nameUz: 'Qora', hexCode: '#000000', inStock: true, priceModifier: 0 },
      { id: '12', nameRu: 'Белый', nameUz: 'Oq', hexCode: '#FFFFFF', inStock: true, priceModifier: 0 },
      { id: '13', nameRu: 'Синий', nameUz: "Ko'k", hexCode: '#3B82F6', inStock: true, priceModifier: 0 },
    ],
    variants: [],
    isActive: true,
    isFeatured: true,
    isNew: false,
    viewCount: 90,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    code: 'P-6',
    slug: 'p-6',
    nameRu: 'Искусственное растение P-6',
    nameUz: "Sun'iy o'simlik P-6",
    descriptionRu: 'Искусственное декоративное растение высокого качества.',
    descriptionUz: "Yuqori sifatli sun'iy dekorativ o'simlik.",
    categoryId: '2',
    price: 315000,
    material: 'plastic',
    inStock: true,
    stockQuantity: 50,
    setQuantity: 50,
    packaging: {
      bags_per_box: 5,
      pcs_per_bag: 10,
      total_pcs: 50,
    },
    images: [
      { id: '6', url: 'https://placehold.co/400x400/4ade80/white?text=P-6', isMain: true, sortOrder: 0 },
    ],
    colors: [],
    variants: [],
    isActive: true,
    isFeatured: false,
    isNew: true,
    viewCount: 60,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]